# Generated by Django 5.1.2 on 2024-11-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCompras',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad_botellas', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_de_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('uniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad_ml', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('marca', models.CharField(max_length=255)),
                ('freignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datoscompras')),
            ],
        ),
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('iniqueId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad_disponible', models.IntegerField()),
                ('foreignKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datoscompras',
            name='foreignKey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userregistro'),
        ),
    ]
