# Generated by Django 5.1.2 on 2024-11-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproductos',
            name='nombre_producto',
        ),
    ]
