# Generated by Django 5.1.2 on 2024-11-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datoscompras_foreignkey2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscompras',
            old_name='foreignKey',
            new_name='DatosPerfu',
        ),
        migrations.RenameField(
            model_name='datoscompras',
            old_name='foreignKey2',
            new_name='DatosProductos',
        ),
        migrations.RenameField(
            model_name='stockproductos',
            old_name='foreignKey',
            new_name='Stock',
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(related_name='relacion_productos', to='api.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userregistro')),
            ],
        ),
    ]
