# Generated by Django 5.1.2 on 2024-12-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productos_genero_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
